# Generated by Django 4.2.1 on 2023-06-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='name',
            new_name='company',
        ),
    ]
